#!/usr/bin/python
#-*-coding:utf-8-*-
import os,sys

STATUS_RTN= {
"OK":0,
"COMMON_ERROR":1,
"UNKNOWN_ACTION":2,
"SUBMIT_ERROR_CHECK":3,
"SUBMIT_ERROR_EXCEPTION":4,
"GET_ERROR_PARMS":5,
"GET_ERROR_NOT_FINISHED":6,
"GET_ERROR_OTHERS":7,
"HANDLER_ERROR_NULL":8,
"HANDLER_ERROR_INVALID":9,
"SERVICE_ERROR":10
}
